# Generated by Django 5.2.6 on 2025-09-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=256)),
                ('surname', models.CharField(blank=True, max_length=256)),
                ('first_names', models.CharField(blank=True, max_length=256)),
                ('date_of_birth', models.CharField(blank=True, max_length=50)),
                ('date_of_death', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown'), ('C', 'Corporate')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('bibliography_sources', models.TextField(blank=True)),
                ('wikidata_id', models.CharField(max_length=256)),
                ('place_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birthplace_of', to='luchtmans.place')),
                ('place_of_death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deathplace_of', to='luchtmans.place')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_relations', to='luchtmans.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_relations', to='luchtmans.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='related_to',
            field=models.ManyToManyField(blank=True, through='luchtmans.PersonPersonRelation', through_fields=('from_person', 'to_person'), to='luchtmans.person'),
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('reverse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luchtmans.relationtype')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='personpersonrelation',
            name='types',
            field=models.ManyToManyField(blank=True, to='luchtmans.relationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='personpersonrelation',
            unique_together={('from_person', 'to_person')},
        ),
    ]
