# Generated by Django 5.2.6 on 2025-09-11 12:44
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0003_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodOfResidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.address')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.person')),
            ],
            options={
                'verbose_name_plural': 'periods of residence',
            },
        ),
    ]
