# Generated by Django 5.2.6 on 2025-09-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0004_periodofresidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.person')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.religion')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='religious_affiliation',
            field=models.ManyToManyField(blank=True, through='luchtmans.PersonReligion', through_fields=('person', 'religion'), to='luchtmans.religion'),
        ),
    ]
