# Generated by Django 5.2.6 on 2025-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0005_religion_personreligion_person_religious_affiliation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='periodofresidence',
            options={'verbose_name': 'period of residence', 'verbose_name_plural': 'periods of residence'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='personpersonrelation',
            options={'verbose_name': 'person person relation', 'verbose_name_plural': 'person person relations'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'ordering': ['text'], 'verbose_name': 'relation type', 'verbose_name_plural': 'relation types'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['name'], 'verbose_name': 'religion', 'verbose_name_plural': 'religions'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'street', 'verbose_name_plural': 'streets'},
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=256, verbose_name='house_number'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='periodofresidence',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='end year'),
        ),
        migrations.AlterField(
            model_name='periodofresidence',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='start year'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bibliography_sources',
            field=models.TextField(blank=True, verbose_name='bibliography sources'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.CharField(blank=True, max_length=50, verbose_name='date of death'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_names',
            field=models.CharField(blank=True, max_length=256, verbose_name='first names'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='related_to',
            field=models.ManyToManyField(blank=True, through='luchtmans.PersonPersonRelation', through_fields=('from_person', 'to_person'), to='luchtmans.person', verbose_name='related to'),
        ),
        migrations.AlterField(
            model_name='person',
            name='religious_affiliation',
            field=models.ManyToManyField(blank=True, through='luchtmans.PersonReligion', through_fields=('person', 'religion'), to='luchtmans.religion', verbose_name='religious affiliation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown'), ('C', 'Corporate')], max_length=1, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_name',
            field=models.CharField(max_length=256, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=256, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='personreligion',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='end year'),
        ),
        migrations.AlterField(
            model_name='personreligion',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='start year'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='text',
            field=models.CharField(max_length=255, unique=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='street',
            name='new_name',
            field=models.CharField(max_length=1024, verbose_name='new name'),
        ),
        migrations.AlterField(
            model_name='street',
            name='old_name',
            field=models.TextField(verbose_name='old name'),
        ),
    ]
