# Generated by Django 5.2.6 on 2025-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0006_alter_address_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_nl',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_nl',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='text_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='text_nl',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='religion',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='religion',
            name='name_nl',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
    ]
