# Generated by Django 5.2.6 on 2025-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0007_country_name_en_country_name_nl_place_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='old_name',
        ),
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='address',
            name='streetname_old',
            field=models.CharField(blank=True, max_length=256, verbose_name='old street name'),
        ),
        migrations.RenameField(
            model_name='street',
            old_name='new_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
    ]
