# Generated by Django 5.2.6 on 2025-10-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0008_remove_street_old_name_address_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenreParisianCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(verbose_name='volume')),
                ('folio', models.CharField(max_length=256, verbose_name='folio')),
                ('recto_verso', models.CharField(choices=[('R', 'Recto'), ('V', 'Verso')], max_length=1, verbose_name='recto or verso')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEditionRelationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonWorkRelationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='STCNGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=256, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=256, verbose_name='short title')),
                ('all_headers', models.TextField(blank=True, verbose_name='all headers')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection', to='luchtmans.person')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stcn_id', models.CharField(blank=True, max_length=256, verbose_name='STCN identifier')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('edition_uncertain', models.BooleanField(verbose_name='edition is uncertain')),
                ('year_of_publication_start', models.IntegerField(null=True, verbose_name='year of publication start')),
                ('year_of_publication_end', models.IntegerField(null=True, verbose_name='year of publication end')),
                ('volumes', models.CharField(blank=True, verbose_name='volumes')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('short_title', models.CharField(max_length=256, verbose_name='short title')),
                ('places_of_publication', models.ManyToManyField(blank=True, to='luchtmans.place', verbose_name='places of publication')),
                ('languages', models.ManyToManyField(blank=True, to='luchtmans.language', verbose_name='languages')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_full', models.CharField(max_length=256, verbose_name='full transcription')),
                ('non_book', models.BooleanField(verbose_name='non book')),
                ('transcription_incomplete', models.BooleanField(verbose_name='transcription is incomplete')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='date_paid')),
                ('edition_uncertain', models.BooleanField(verbose_name='edition is uncertain')),
                ('volumes', models.CharField(default='1', max_length=10, verbose_name='volumes')),
                ('number_of_copies', models.CharField(default='1', max_length=10, verbose_name='number of copies')),
                ('price', models.CharField(blank=True, max_length=20, verbose_name='price')),
                ('price_decimal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='decimal price')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('work_in_progress', models.BooleanField(verbose_name='work in progress')),
                ('binding', models.ManyToManyField(blank=True, to='luchtmans.binding', verbose_name='bindings')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.collection')),
                ('editions', models.ManyToManyField(to='luchtmans.edition', verbose_name='editions')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.itemtype')),
                ('languages', models.ManyToManyField(blank=True, to='luchtmans.language', verbose_name='languages')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.page')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEditionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.edition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.personeditionrelationrole')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='persons',
            field=models.ManyToManyField(blank=True, through='luchtmans.PersonEditionRelation', through_fields=('edition', 'person'), to='luchtmans.person', verbose_name='authors'),
        ),
        migrations.CreateModel(
            name='PersonWorkRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.personworkrelationrole')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='stcn_genres',
            field=models.ManyToManyField(blank=True, to='luchtmans.stcngenre', verbose_name='STCN genres'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('uncertain', models.BooleanField(verbose_name='uncertain')),
                ('viaf_id', models.CharField(blank=True, max_length=256, verbose_name='VIAF identifier')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('authors', models.ManyToManyField(through='luchtmans.PersonWorkRelation', through_fields=('work', 'person'), to='luchtmans.person', verbose_name='authors')),
                ('genre_parisian_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='luchtmans.genreparisiancategory')),
                ('languages', models.ManyToManyField(blank=True, to='luchtmans.language', verbose_name='languages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='personworkrelation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.work'),
        ),
        migrations.AddField(
            model_name='edition',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.work'),
        ),
    ]
