# Generated by Django 5.2.6 on 2025-10-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0009_binding_format_genreparisiancategory_itemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='year_of_publication_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='year of publication end'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='year_of_publication_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='year of publication start'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='decimal price'),
        ),
    ]
