# Generated by Django 5.2.6 on 2025-10-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0010_alter_edition_year_of_publication_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binding',
            options={'verbose_name': 'binding', 'verbose_name_plural': 'bindings'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'edition', 'verbose_name_plural': 'editions'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'format', 'verbose_name_plural': 'formats'},
        ),
        migrations.AlterModelOptions(
            name='genreparisiancategory',
            options={'verbose_name': 'genre Parisian category', 'verbose_name_plural': 'genre Parisian categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'item type', 'verbose_name_plural': 'item type'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='personeditionrelation',
            options={'verbose_name': 'person edition relation', 'verbose_name_plural': 'person edition relations'},
        ),
        migrations.AlterModelOptions(
            name='personeditionrelationrole',
            options={'verbose_name': 'person edition relation role', 'verbose_name_plural': 'person edition relation roles'},
        ),
        migrations.AlterModelOptions(
            name='personworkrelation',
            options={'verbose_name': 'person work relation', 'verbose_name_plural': 'person work relations'},
        ),
        migrations.AlterModelOptions(
            name='personworkrelationrole',
            options={'verbose_name': 'person work relation role', 'verbose_name_plural': 'person work relation roles'},
        ),
        migrations.AlterModelOptions(
            name='stcngenre',
            options={'verbose_name': 'STCN genre', 'verbose_name_plural': 'STCN genres'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'work', 'verbose_name_plural': 'works'},
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=256, verbose_name='house number'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection', to='luchtmans.person', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.work', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.collection', verbose_name='collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.itemtype', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personeditionrelation',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.edition', verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='personeditionrelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='personeditionrelation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.personeditionrelationrole', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='personworkrelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='personworkrelation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luchtmans.personworkrelationrole', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='personworkrelation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchtmans.work', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='genre_parisian_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='luchtmans.genreparisiancategory', verbose_name='genre Parisian category'),
        ),
    ]
