# Generated by Django 5.2.6 on 2025-11-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0011_alter_binding_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
