# Generated by Django 5.2.6 on 2025-11-25 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0011_alter_binding_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='binding',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='country',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='edition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='format',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='genreparisiancategory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='language',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='periodofresidence',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='personeditionrelationrole',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='personpersonrelation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='personreligion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='personworkrelation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='personworkrelationrole',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='place',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='religion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='stcngenre',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='street',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='work',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
    ]
