# Generated by Django 5.2.6 on 2026-05-21 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0014_remove_address_latitude_remove_address_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['volume', 'folio', 'recto_verso'], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AddField(
            model_name='edition',
            name='tags',
            field=models.ManyToManyField(blank=True, to='luchtmans.editiontag'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='luchtmans.itemtag'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, to='luchtmans.persontag'),
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, to='luchtmans.worktag'),
        ),
    ]
