# Generated by Django 5.2.6 on 2026-09-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchtmans', '0015_editiontag_itemtag_persontag_worktag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InDBSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDITION_AUTHOR_ROLE', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indb_author_role', to='luchtmans.personeditionrelationrole')),
                ('EDITION_PRODUCER_ROLE', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indb_producer_role', to='luchtmans.personeditionrelationrole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
